baseURL = "https://photos.sjbdcs.org/"
languageCode = "en-us"
title = "St John Photo Gallery"

[menu]
  [[menu.main]]
    identifier = "top"
    name = "Index"
    url = "/"
  [[menu.main]]
    identifier = "photos_m"
    name = "Photo gallery (masonry)"
    url = "/photos_m/"
  [[menu.main]]
    identifier = "photos_s"
    name = "Photo gallery (square)"
    url = "/photos_s/"
  [[menu.main]]
    identifier = "photos_s"
    name = "Photo gallery (square)"
    url = "/photos_s/"
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "https://sjbdcs.org"
